### ISSUE TITLE
Zbrisan komentar se ne odšteje

### ISSUE THREAD

**Issue by ramuta** [smartninja/forum#16]
Ko zbrišeš komentar, se ne odšteje od števila komentarjev shranjenega v Topic modelu

**Comment by DavorPadovan** [comment]
Ojoj, to bo pa potrebno popraviti! :)

**Comment by ramuta** [comment]
Tako pa res ne gre... ti ti @ekranac! :D

**Comment by DavorPadovan** [comment]
https://github.com/smartninja/forum/commit/f3847afea84a7722ecb429e3b110e0767b89c196
