### ISSUE TITLE
Zakaj je bil index.html prepisan?

### ISSUE THREAD

**Issue by ramuta** [smartninja/forum#32]
@ekranac Zakaj, si mi zbrisal instructor filter v index.html? https://github.com/smartninja/forum/commit/5f210d736235b1f3a30caeca40f3bca74f8ebefb ???

CC @DavorPadovan

**Comment by DavorPadovan** [comment]
Fixed in https://github.com/smartninja/forum/commit/7ed799e964c6e34644c928552126f9fa5db4add2.
