### ISSUE TITLE
Dekoratorji namesto if stavkov

### ISSUE THREAD

**Issue by DavorPadovan** [smartninja/forum#33]
Smiselno bi bilo vpeljati dekoratorje za preverjanje, če je obiskovalec prijavljen/admin.

**Comment by ramuta** [comment]
Agree :) Kar naj to @ekranac naredi, da se nauči :)

**Comment by DavorPadovan** [comment]
https://github.com/smartninja/forum/commit/0e9a6bdd7bfedc0e0652bba146e376448176184d
