### ISSUE TITLE
Public forum?

### ISSUE THREAD

**Issue by ramuta** [smartninja/forum#6]
Jaz bi dal dostopnost do objav na forumu na public - zato ker nam to lahko generira nov trafic na website (nove prijave na tečaje) #contentmarketing

**Comment by DavorPadovan** [comment]
Like!

**Comment by ekranac** [comment]
Misliš, da je to taka vsebina, ki bi pripeljala nove ljudi na naše tečaje? 
Mogoče bi dal le toliko, da se vidijo topici, ko pa klikneš gor pa zahteva prijavo

**Comment by ramuta** [comment]
Ma ko bi folk guglal za kak programerski problem, bi lahko naletu na kak
topic iz našega foruma in tako izvedel za smartninjo. Content marketing ;)

2015-04-21 13:32 GMT+02:00 Ziga Besal notifications@github.com:
