### ISSUE TITLE
Omogoči markdown

### ISSUE THREAD

**Issue by ramuta** [smartninja/forum#8]
Omogoči markdown v topicih in komentarjih, da bo lažje odgovarjat na vprašanja (primer: http://smartninjaforum.appspot.com/topic/5644406560391168)

**Comment by DavorPadovan** [comment]
Done!

**Comment by DavorPadovan** [comment]
https://github.com/smartninja/forum/pull/11

**Comment by DavorPadovan** [comment]
https://github.com/smartninja/forum/commit/89686652937206a32c72e4488881da5e449a3cde
